# Generated by Django 2.2.16 on 2022-11-05 04:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20221105_0050'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='введите текст комментария', verbose_name='текст комментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата комментария')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL, verbose_name='автор комментария')),
                ('post', models.ForeignKey(blank=True, help_text='комментарий к посту', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='posts.Post', verbose_name='комментарий')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
